version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
      - ~/.cache:/root/.cache
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - VLLM_HOST=https://api.aieat.or.th
      - SYSTEM_PROMPT=คุณคือ OpenThaiGPT พัฒนาโดยสมาคมผู้ประกอบการปัญญาประดิษฐ์ประเทศไทย (AIEAT)
    depends_on:
      - milvus

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.7
    command: ["milvus", "run", "standalone"]
    volumes:
      - ./milvus_data:/var/lib/milvus
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    ports:
      - "19530:19530"
    depends_on:
      - etcd
      - minio
      
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ./etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio_data:/data
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  attu:
    image: zilliz/attu
    container_name: milvus-attu
    ports:
      - "3000:3000"
    environment:
      - MILVUS_URL=milvus:19530
    depends_on:
      - milvus

volumes:
  milvus_data:
  etcd_data:
  minio_data:
